---
- name: apt update on all hosts
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes


- name: Configure HA load balancers
  hosts: lb
  gather_facts: true
  vars:
    # Override interface if not eth0
    keepalived_interface: "{{ hostvars[inventory_hostname].keepalived_interface | default('eth0') }}"
  roles:
    - haproxy
    - keepalived

- name: Configure NFS servers
  hosts: nfs-servers
  gather_facts: true
  roles:
    - nfs-server

- name: Configure NFS clients
  hosts: nfs-clients
  gather_facts: true
  roles:
    - nfs-client