apiVersion: v1
kind: Namespace
metadata:
  name: db
---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: db
spec:
  instances: 3
  bootstrap:
    initdb:
      database: passbolt-db
      owner: passbolt
      secret:
        name: passboltdb-user-secret
  storage:
    storageClass: nfs-client
    size: 10Gi
---

apiVersion: v1
kind: Secret
metadata:
  name: passboltdb-user-secret
  namespace: db
type: Opaque
stringData:
  username: passbolt
  password: zaq12wsx

